# Generated by Django 5.2.8 on 2025-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True, verbose_name='Английское слово')),
                ('russian_translation', models.CharField(max_length=100, verbose_name='Русский перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Слово в словаре',
                'verbose_name_plural': 'Словарь',
                'ordering': ['english_word'],
            },
        ),
    ]
